### ISSUE TITLE
CONFIG_IMA_DIRECTORIES missing from the docs

### ISSUE THREAD

**Issue by zvonkok** [linux-integrity/ima-doc#2]
As title already says, I am missing CONFIG_IMA_DIRECTORIES in the docs

**Comment by kgoldman** [comment]
Is this upstreamed in the kernel?  I found some proposals from 2014. I don't see it in the master branch.

**Comment by kgoldman** [comment]
Closed - no response - the flag does not appear in a recent kernel.
